export const GET_CART_BY_USER_REQUEST = 'GET_CART_BY_USER_REQUEST'
export const GET_CART_BY_USER_SUCCESS = 'GET_CART_BY_USER_SUCCESS'
export const GET_CART_BY_USER_FAILURE = 'GET_CART_BY_USER_FAILURE'

export const POST_ITEM_TO_CART_REQUEST = 'POST_ITEM_TO_CART_REQUEST'
export const POST_ITEM_TO_CART_SUCCESS = 'POST_ITEM_TO_CART_SUCCESS'
export const POST_ITEM_TO_CART_FAILURE = 'POST_ITEM_TO_CART_FAILURE'

export const DELETE_ITEM_FROM_CART_REQUEST = 'DELETE_ITEM_FROM_CART_REQUEST'
export const DELETE_ITEM_FROM_CART_SUCCESS = 'DELETE_ITEM_FROM_CART_SUCCESS'
export const DELETE_ITEM_FROM_CART_FAILURE = 'DELETE_ITEM_FROM_CART_FAILURE'

export const PUT_ITEM_OF_CART_REQUEST = 'PUT_ITEM_OF_CART_REQUEST'
export const PUT_ITEM_OF_CART_SUCCESS = 'PUT_ITEM_OF_CART_SUCCESS'
export const PUT_ITEM_OF_CART_FAILURE = 'PUT_ITEM_OF_CART_FAILURE'