export const GET_ADDRESS_REQUEST = 'GET_ADDRESS_REQUEST'
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS'
export const GET_ADDRESS_FAILURE = 'GET_ADDRESS_FAILURE'

export const PUT_ADDRESS_REQUEST = 'PUT_ADDRESS_REQUEST'
export const PUT_ADDRESS_SUCCESS = 'PUT_ADDRESS_SUCCESS'
export const PUT_ADDRESS_FAILURE = 'PUT_ADDRESS_FAILURE'

export const POST_ADDRESS_REQUEST = 'POST_ADDRESS_REQUEST'
export const POST_ADDRESS_SUCCESS = 'POST_ADDRESS_SUCCESS'
export const POST_ADDRESS_FAILURE = 'POST_ADDRESS_FAILURE'

export const DELETE_ADDRESS_REQUEST = 'DELETE_ADDRESS_REQUEST'
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS'
export const DELETE_ADDRESS_FAILURE = 'DELETE_ADDRESS_FAILURE'

export const FIND_ADDRESS_BY_ID_REQUEST = 'FIND_ADDRESS_BY_ID_REQUEST'
export const FIND_ADDRESS_BY_ID_SUCCESS = 'FIND_ADDRESS_BY_ID_SUCCESS'
export const FIND_ADDRESS_BY_ID_FAILURE = 'FIND_ADDRESS_BY_ID_FAILURE'